app="myapp"

http=[
  ["get", "/"],
  ["post", "/login"],
  ["post", "/logout"],
  ["post", "/posts"],
  ["patch", "/posts/:postID"],
  ["delete", "/posts/:postID"],
  ["get", "/posts/:postID"],
]

events=["foo"]
queues=["bar"]
ws=["join"]
macros=["storage"]

[scheduled]
daily=["rate(1 day)"]

[aws]
profile="myprofile"
region="ca-central-1"
bucket="mybucket-central-1"

[cdn]
# no config

[static]
folder="dist"
fingerprint=true

[[tables]]
[tables.data]
scopeID="*String"
dataID="**String"
stream=true
ttl="TTL"
